# Generated by Django 3.2.9 on 2021-11-19 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='기기 등록 날짜'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(default='TBD', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='기기 소유주'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.serial'),
        ),
        migrations.AlterField(
            model_name='history',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='history테이블에 기록된 시간'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성날짜'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='시리얼 넘버 생성 날짜'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='만료 날짜'),
        ),
        migrations.AlterField(
            model_name='status',
            name='IP',
            field=models.GenericIPAddressField(null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='status',
            name='ONF',
            field=models.BooleanField(default=True, verbose_name='디바이스 On/Off'),
        ),
        migrations.AlterField(
            model_name='status',
            name='device_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.device'),
        ),
        migrations.CreateModel(
            name='Regist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='관계 등록 날짜')),
                ('device_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.device', verbose_name='디바이스 ID')),
                ('progete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered_protege', to=settings.AUTH_USER_MODEL, verbose_name='피보호자')),
                ('protector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered_protector', to=settings.AUTH_USER_MODEL, verbose_name='보호자')),
            ],
        ),
    ]
